language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install .
  - cd ..
  - git clone https://github.com/udst/variable_generators.git
  - cd variable_generators
  - pip install .
  - cd ../zone_model/zone_model/data
  - curl -O https://storage.googleapis.com/urbansim/zone_model/model_data.h5
  - cd ..

script:
- python simulate.py
# - python evaluate.py # Commenting out for now as interaction terms warrant a revisit of evaluate
