language: python
sudo: false
python:
- '2.7'
- '3.5'

install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- |
  conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy pandas pytest matplotlib scipy statsmodels pyyaml pycodestyle scikit-learn
- source activate test-environment
- conda list
- pip install .
- cd .. && git clone git@github.com:urbansim/variable_generators.git
- cd variable_generators && pip install .
- cd $TRAVIS_BUILD_DIR && pip install .
- cd zone_model/data && curl -O https://storage.googleapis.com/urbansim/zone_model/model_data.h5
- cd $TRAVIS_BUILD_DIR/zone_model

script:
- pycodestyle .
- python simulate.py
# - python evaluate.py # Commenting out for now as interaction terms warrant a revisit of evaluate
