name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: null

choosers_predict_filters: aggr_sector_id == 1

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    density_residential_units: null
    mean_year_built: null
    nodes_jobs_10km: null
    nodes_jobs_5000m_54: null
    res_btype_mode1: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        density_residential_units: -0.3097960214712745
        mean_year_built: 0.025373016820451393
        nodes_jobs_10km: 0.2537874226870059
        nodes_jobs_5000m_54: 0.16946988506077076
        res_btype_mode1: -0.6684656636551434
    Std. Error:
        density_residential_units: 0.015317938039211207
        mean_year_built: 0.00019833646600599106
        nodes_jobs_10km: 0.05234049114938242
        nodes_jobs_5000m_54: 0.03494853719777215
        res_btype_mode1: 0.07353310316114377
    T-Score:
        density_residential_units: -20.224394476479247
        mean_year_built: 127.92915660645562
        nodes_jobs_10km: 4.848778013234222
        nodes_jobs_5000m_54: 4.849126705983388
        res_btype_mode1: -9.090676646547031

probability_mode: single_chooser

log_likelihoods:
    convergence: -3491.54628790054
    'null': -3912.023005428176
    ratio: 0.10748319141891505
