name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: null

choosers_predict_filters: all_jobs == 1

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression:
- x
- land_km2
- total_number_of_jobs
- ln_residential_units

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        land_km2: -0.0077205532596799865
        ln_residential_units: 0.16497847984053593
        total_number_of_jobs: 3.756373464544267e-05
        x: -1.1686192371427047
    Std. Error:
        land_km2: 0.0016530420349876943
        ln_residential_units: 0.018617424176526086
        total_number_of_jobs: 1.1837983289839773e-06
        x: 0.0013887261429810938
    T-Score:
        land_km2: -4.6705123622203955
        ln_residential_units: 8.861509426666565
        total_number_of_jobs: 31.731532074118256
        x: -841.5044557554745

probability_mode: single_chooser

log_likelihoods:
    convergence: -3326.962222626495
    'null': -3912.023005428176
    ratio: 0.14955453533628826
