name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: null

choosers_predict_filters: aggr_sector_id == 5

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    density_households: null
    mean_year_built: null
    nodes_jobs_10km: null
    nodes_jobs_5000m_56: null
    res_btype_mode2: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        density_households: -0.016386942683394818
        mean_year_built: 0.01432310154508792
        nodes_jobs_10km: 0.25425805540607427
        nodes_jobs_5000m_56: 0.3371886620761602
        res_btype_mode2: 0.270809176984807
    Std. Error:
        density_households: 0.007844131661512765
        mean_year_built: 0.00019099590426897918
        nodes_jobs_10km: 0.05111162230141275
        nodes_jobs_5000m_56: 0.03476965691717387
        res_btype_mode2: 0.15430026765636246
    T-Score:
        density_households: -2.08907032550172
        mean_year_built: 74.99166853817306
        nodes_jobs_10km: 4.974564374158917
        nodes_jobs_5000m_56: 9.69778513717838
        res_btype_mode2: 1.7550791135885653

probability_mode: single_chooser

log_likelihoods:
    convergence: -3589.4067967566184
    'null': -3912.023005428176
    ratio: 0.08246787102834197
