name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: null

choosers_predict_filters: aggr_sector_id == 4

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: block_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    block_groups_ratio_households_to_residential_units: null
    counties_total_jobs: null
    nodes_high_income_hh_5000m: null
    nodes_jobs_10km: null
    nodes_post2010_du_3000m: null
    res_btype_mode4: null
    tracts_density_households: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        block_groups_ratio_households_to_residential_units: 2.069098387088777
        counties_total_jobs: 1.0269713579995985e-05
        nodes_high_income_hh_5000m: 0.3801551889440009
        nodes_jobs_10km: 0.39059877984224417
        nodes_post2010_du_3000m: 0.539798033992424
        res_btype_mode4: 1.4094745130131237
        tracts_density_households: -0.6748998102254922
    Std. Error:
        block_groups_ratio_households_to_residential_units: 0.3266324713216005
        counties_total_jobs: 1.5909942799825176e-06
        nodes_high_income_hh_5000m: 0.09691723859700516
        nodes_jobs_10km: 0.06062066290924649
        nodes_post2010_du_3000m: 0.03810458812472912
        res_btype_mode4: 0.0772826552503072
        tracts_density_households: 0.06529384357759638
    T-Score:
        block_groups_ratio_households_to_residential_units: 6.334637761876266
        counties_total_jobs: 6.454902892616831
        nodes_high_income_hh_5000m: 3.922472353187208
        nodes_jobs_10km: 6.443327424957374
        nodes_post2010_du_3000m: 14.16622145935507
        res_btype_mode4: 18.237915201645727
        tracts_density_households: -10.336346786254497

probability_mode: single_chooser

log_likelihoods:
    convergence: -2828.5685016564967
    'null': -3912.023005428176
    ratio: 0.2769550440445566
