name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: recent_mover == 1

choosers_predict_filters: income_quartile == 3

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    density_residential_units: null
    nodes_high_income_hh_1500m: null
    nodes_jobs_10km: null
    nodes_post2000_du_800m: null
    ratio_households_to_residential_units: null
    res_btype_mode2: null
    res_value: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        density_residential_units: 0.031108994650985537
        nodes_high_income_hh_1500m: 0.35410184613107193
        nodes_jobs_10km: 0.12002600276148503
        nodes_post2000_du_800m: 0.21433213306264323
        ratio_households_to_residential_units: 1.5825417999209301
        res_btype_mode2: -1.2054098149709334
        res_value: -2.492961549363292e-06
    Std. Error:
        density_residential_units: 0.008510666613976259
        nodes_high_income_hh_1500m: 0.0480307296469968
        nodes_jobs_10km: 0.02585837385855181
        nodes_post2000_du_800m: 0.02112007340395871
        ratio_households_to_residential_units: 0.3625350671855871
        res_btype_mode2: 0.385149170473467
        res_value: 3.9212606157427654e-07
    T-Score:
        density_residential_units: 3.65529470980548
        nodes_high_income_hh_1500m: 7.37240197543434
        nodes_jobs_10km: 4.641668629978074
        nodes_post2000_du_800m: 10.148266483887749
        ratio_households_to_residential_units: 4.365210273881736
        res_btype_mode2: -3.129721955493539
        res_value: -6.357551291935935

probability_mode: single_chooser

log_likelihoods:
    convergence: -3721.1636921760874
    'null': -3912.023005428176
    ratio: 0.0487878811007143
