name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: null

choosers_predict_filters: income_quartile == 1

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression:
- avg_residential_value
- y
- ln_residential_units

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        avg_residential_value: -0.0017985572558068797
        ln_residential_units: 1.1454876550005044
        y: -0.6522619831771769
    Std. Error:
        avg_residential_value: 0.0004227497021857127
        ln_residential_units: 0.044573867688738375
        y: 0.012411679216790393
    T-Score:
        avg_residential_value: -4.254425837577004
        ln_residential_units: 25.69863721495976
        y: -52.55227530331299

probability_mode: single_chooser

log_likelihoods:
    convergence: -3397.310749172847
    'null': -3912.023005428176
    ratio: 0.13157188890278348
