{alts_fit_filters: null, alts_predict_filters: null, choice_column: block_id, choice_mode: aggregate,
  choosers_fit_filters: recent_mover == 1, choosers_predict_filters: income_quartile
    == 4, estimation_sample_size: 1000, fit_parameters: {Coefficient: {block_groups_total_households: 0.0003000820369453005,
      county_id_is_27009: 0.06, county_id_is_27141: 0.06, county_id_is_27145: -0.06,
      nodes_ave_year_built_5000m: 0.05145014235618972, nodes_high_income_hh_1500m: 0.6062568604997931,
      nodes_jobs_10km: 0.004631756857704014, res_btype_mode1: 1.1846411552062566},
    Std. Error: {block_groups_total_households: 8.013171439907699e-05, nodes_ave_year_built_5000m: 0.00010409075195466312,
      nodes_high_income_hh_1500m: 0.042304115625607555, nodes_jobs_10km: 0.02485185408255947,
      res_btype_mode1: 0.09308642967252026}, T-Score: {block_groups_total_households: 3.7448598123186674,
      nodes_ave_year_built_5000m: 494.28158976696517, nodes_high_income_hh_1500m: 14.330919144254922,
      nodes_jobs_10km: 0.18637470034698486, res_btype_mode1: 12.726249780702144}},
  fitted: true, interaction_predict_filters: null, log_likelihoods: {convergence: -3304.5283056083063,
    'null': -3912.023005428176, ratio: 0.15528914297715857}, model_expression: !!set {
    block_groups_total_households: null, county_id_is_27009: null, county_id_is_27141: null,
    county_id_is_27145: null, nodes_ave_year_built_5000m: null, nodes_high_income_hh_1500m: null,
    nodes_jobs_10km: null, res_btype_mode1: null}, model_type: discretechoice, name: MNLDiscreteChoiceModel,
  prediction_sample_size: null, probability_mode: single_chooser, sample_size: 50}
