name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: recent_mover == 1

choosers_predict_filters: income_quartile == 3

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: block_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    counties_mean_income: null
    density_residential_units: null
    nodes_jobs_10km: null
    nodes_post2000_du_800m: null
    ratio_households_to_residential_units: null
    res_btype_mode1: null
    tracts_total_households: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        counties_mean_income: 3.181990557876308e-05
        density_residential_units: 0.08121764888349348
        nodes_jobs_10km: 0.08310315687232023
        nodes_post2000_du_800m: 0.36500157923840904
        ratio_households_to_residential_units: 3.0
        res_btype_mode1: -0.21532697833348205
        tracts_total_households: 0.00033210438597136793
    Std. Error:
        counties_mean_income: 3.888319626491367e-06
        density_residential_units: 0.007420453023507764
        nodes_jobs_10km: 0.02076546868228591
        nodes_post2000_du_800m: 0.02893566674858219
        ratio_households_to_residential_units: 0.3336332370894756
        res_btype_mode1: 0.08571692029903549
        tracts_total_households: 4.5870127947800236e-05
    T-Score:
        counties_mean_income: 8.183459343715485
        density_residential_units: 10.94510653543638
        nodes_jobs_10km: 4.0019880188503425
        nodes_post2000_du_800m: 12.614244641737644
        ratio_households_to_residential_units: 8.991909877358662
        res_btype_mode1: -2.5120708674819827
        tracts_total_households: 7.240101583089097

probability_mode: single_chooser

log_likelihoods:
    convergence: -2922.283577932879
    'null': -3912.023005428176
    ratio: 0.2529993883272087
