name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: recent_mover == 1

choosers_predict_filters: income_quartile == 4

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    density_households: null
    nodes_high_income_hh_1500m: null
    nodes_jobs_35km: null
    nodes_post2000_du_800m: null
    ratio_households_to_residential_units: null
    res_btype_mode1: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        density_households: 0.02840018555778312
        nodes_high_income_hh_1500m: 0.7810798044374292
        nodes_jobs_35km: 0.0284749822304958
        nodes_post2000_du_800m: 0.1253560481782114
        ratio_households_to_residential_units: 2.0043588354532096
        res_btype_mode1: -0.2572381395033422
    Std. Error:
        density_households: 0.010172950125919442
        nodes_high_income_hh_1500m: 0.05175279614778087
        nodes_jobs_35km: 0.032666045920411446
        nodes_post2000_du_800m: 0.020940286234791956
        ratio_households_to_residential_units: 0.4934572263063256
        res_btype_mode1: 0.10673960449497359
    T-Score:
        density_households: 2.7917354559148873
        nodes_high_income_hh_1500m: 15.092514078022845
        nodes_jobs_35km: 0.8716996939229534
        nodes_post2000_du_800m: 5.986357911857684
        ratio_households_to_residential_units: 4.061869456156176
        res_btype_mode1: -2.4099596463790123

probability_mode: single_chooser

log_likelihoods:
    convergence: -3624.3885201640164
    'null': -3912.023005428176
    ratio: 0.07352576527925547
