{alts_fit_filters: null, alts_predict_filters: null, choice_column: block_id, choice_mode: aggregate,
  choosers_fit_filters: recent_mover == 1, choosers_predict_filters: income_quartile
    == 3, estimation_sample_size: 1000, fit_parameters: {Coefficient: {counties_median_income: 3.0881290478519295e-05,
      county_id_is_27009: 0.06, county_id_is_27141: 0.06, county_id_is_27145: -0.06,
      mean_value: -5.00295051500266e-06, nodes_ave_year_built_800m: 0.019114119178426116,
      nodes_households_25km: 0.14428887429802245, nodes_jobs_10km: 0.11702433118330532,
      ratio_households_to_residential_units: 3.0, tracts_total_households: 0.0002743257864553967},
    Std. Error: {counties_median_income: 5.110588862953893e-06, mean_value: 9.132422832871016e-07,
      nodes_ave_year_built_800m: 0.00030682600040643097, nodes_households_25km: 0.06576519390172406,
      nodes_jobs_10km: 0.03731872035270892, ratio_households_to_residential_units: 0.37458544537927174,
      tracts_total_households: 4.490225439673914e-05}, T-Score: {counties_median_income: 6.042609043035028,
      mean_value: -5.478229169366934, nodes_ave_year_built_800m: 62.296282430781545,
      nodes_households_25km: 2.1940005911582947, nodes_jobs_10km: 3.135807714661113,
      ratio_households_to_residential_units: 8.008853619399089, tracts_total_households: 6.109398963169177}},
  fitted: true, interaction_predict_filters: null, log_likelihoods: {convergence: -3053.361715529004,
    'null': -3912.023005428176, ratio: 0.2194929039803002}, model_expression: !!set {
    counties_median_income: null, county_id_is_27009: null, county_id_is_27141: null,
    county_id_is_27145: null, mean_value: null, nodes_ave_year_built_800m: null, nodes_households_25km: null,
    nodes_jobs_10km: null, ratio_households_to_residential_units: null, tracts_total_households: null},
  model_type: discretechoice, name: MNLDiscreteChoiceModel, prediction_sample_size: null,
  probability_mode: single_chooser, sample_size: 50}
