{alts_fit_filters: null, alts_predict_filters: null, choice_column: block_id, choice_mode: aggregate,
  choosers_fit_filters: recent_mover == 1, choosers_predict_filters: income_quartile
    == 2, estimation_sample_size: 1000, fit_parameters: {Coefficient: {block_groups_median_value: -2.7526541743529776e-06,
      counties_total_households: 2.491591959976493e-05, county_id_is_27009: 0.06,
      county_id_is_27141: 0.06, county_id_is_27145: -0.06, density_residential_units: 0.12120237376143862,
      nodes_jobs_15km: 0.12165165325281965, nodes_post2000_du_800m: 0.41780758918642164,
      pumas_mean_income: 0.00015465369438179584, ratio_households_to_residential_units: 3.0,
      res_btype_mode4: 1.3879681666971038}, Std. Error: {block_groups_median_value: 8.458903155668795e-07,
      counties_total_households: 2.197262563071675e-06, density_residential_units: 0.006638808262086936,
      nodes_jobs_15km: 0.024267438203705204, nodes_post2000_du_800m: 0.02694918052830818,
      pumas_mean_income: 5.422136828557886e-06, ratio_households_to_residential_units: 0.38235265121883,
      res_btype_mode4: 0.08000856566014523}, T-Score: {block_groups_median_value: -3.254150241108112,
      counties_total_households: 11.339527655235516, density_residential_units: 18.256646219714465,
      nodes_jobs_15km: 5.012958196561746, nodes_post2000_du_800m: 15.503535951586532,
      pumas_mean_income: 28.522646932709137, ratio_households_to_residential_units: 7.84615979629503,
      res_btype_mode4: 17.34774464765207}}, fitted: true, interaction_predict_filters: null,
  log_likelihoods: {convergence: -2533.360004589427, 'null': -3912.023005428176, ratio: 0.3524168950248422},
  model_expression: !!set {block_groups_median_value: null, counties_total_households: null,
    county_id_is_27009: null, county_id_is_27141: null, county_id_is_27145: null,
    density_residential_units: null, nodes_jobs_15km: null, nodes_post2000_du_800m: null,
    pumas_mean_income: null, ratio_households_to_residential_units: null, res_btype_mode4: null},
  model_type: discretechoice, name: MNLDiscreteChoiceModel, prediction_sample_size: null,
  probability_mode: single_chooser, sample_size: 50}
