name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: recent_mover == 1

choosers_predict_filters: income_quartile == 1

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    nodes_ave_year_built_800m: null
    nodes_high_income_hh_3000m: null
    nodes_jobs_10km: null
    res_btype_mode4: null
    res_rent: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        nodes_ave_year_built_800m: 0.002598772330963231
        nodes_high_income_hh_3000m: 0.059691943546341
        nodes_jobs_10km: 0.24247547097542713
        res_btype_mode4: 1.1015605246568685
        res_rent: -0.0011201495064102117
    Std. Error:
        nodes_ave_year_built_800m: 0.00019412810206910922
        nodes_high_income_hh_3000m: 0.044408100350271706
        nodes_jobs_10km: 0.03155634278840991
        res_btype_mode4: 0.07356625145649948
        res_rent: 0.00015722565537712305
    T-Score:
        nodes_ave_year_built_800m: 13.386894031643461
        nodes_high_income_hh_3000m: 1.3441679125095873
        nodes_jobs_10km: 7.68389013268306
        res_btype_mode4: 14.973721004504807
        res_rent: -7.124470263605578

probability_mode: single_chooser

log_likelihoods:
    convergence: -3532.4424779293654
    'null': -3912.023005428176
    ratio: 0.09702921659001462
