template: zone

geography: zones

geography_id: zone_id

base_year: 2010

models: 

    elcm:
        model_type: location_choice
        agents_name: jobs
        alternatives_id_name: zone_id
        alternatives_name: zones
        choosers_fit_filter: null
        segmentation_variable: sector_id

    hlcm: 
        model_type: location_choice
        agents_name: households
        alternatives_id_name: zone_id
        alternatives_name: zones
        choosers_fit_filter: recent_mover == 1
        segmentation_variable: income_quartile

    rdplcm: 
        model_type: location_choice
        agents_name: residential_units
        alternatives_id_name: zone_id
        alternatives_name: zones

    nrdplcm: 
        model_type: location_choice
        agents_name: residential_units
        alternatives_id_name: zone_id
        alternatives_name: zones
