name: networks

desc: Neighborhood Accessibility Variables

model_type: networks

node_col: node_id

variable_definitions:

  - name: jobs_40km
    dataframe: jobs
    radius: 40000
    apply: np.log1p

  - name: jobs_35km
    dataframe: jobs
    radius: 35000
    apply: np.log1p

  - name: jobs_30km
    dataframe: jobs
    radius: 30000
    apply: np.log1p

  - name: jobs_25km
    dataframe: jobs
    radius: 25000
    apply: np.log1p

  - name: jobs_20km
    dataframe: jobs
    radius: 20000
    apply: np.log1p

  - name: jobs_15km
    dataframe: jobs
    radius: 15000
    apply: np.log1p

  - name: jobs_10km
    dataframe: jobs
    radius: 10000
    apply: np.log1p

  - name: jobs_5000m
    dataframe: jobs
    radius: 5000
    apply: np.log1p

  - name: jobs_3000m
    dataframe: jobs
    radius: 3000
    apply: np.log1p

  - name: jobs_1500m
    dataframe: jobs
    radius: 1500
    apply: np.log1p
    
  - name: jobs_800m
    dataframe: jobs
    radius: 800
    apply: np.log1p
    
  - name: jobs_400m
    dataframe: jobs
    radius: 400
    apply: np.log1p

  - name: jobs_20km_agg0
    dataframe: jobs
    filters:
    - aggr_sector_id == 0
    radius: 20000
    apply: np.log1p

  - name: jobs_20km_agg1
    dataframe: jobs
    filters:
    - aggr_sector_id == 1
    radius: 20000
    apply: np.log1p

  - name: jobs_20km_agg2
    dataframe: jobs
    filters:
    - aggr_sector_id == 2
    radius: 20000
    apply: np.log1p

  - name: jobs_20km_agg3
    dataframe: jobs
    filters:
    - aggr_sector_id == 3
    radius: 20000
    apply: np.log1p

  - name: jobs_20km_agg4
    dataframe: jobs
    filters:
    - aggr_sector_id == 4
    radius: 20000
    apply: np.log1p

  - name: jobs_20km_agg5
    dataframe: jobs
    filters:
    - aggr_sector_id == 5
    radius: 20000
    apply: np.log1p

  - name: high_income_hh_20km
    dataframe: households
    filters:
    - income > 100000
    radius: 20000
    apply: np.log1p

  - name: du_20km
    dataframe: residential_units
    radius: 20000
    apply: np.log1p

  - name: population_20km
    dataframe: households
    varname: persons
    radius: 20000
    aggregation: sum
    decay: flat
    apply: np.log1p

  - name: households_40km
    dataframe: households
    radius: 40000
    apply: np.log1p

  - name: households_35km
    dataframe: households
    radius: 35000
    apply: np.log1p

  - name: households_30km
    dataframe: households
    radius: 30000
    apply: np.log1p

  - name: households_25km
    dataframe: households
    radius: 25000
    apply: np.log1p

  - name: households_20km
    dataframe: households
    radius: 20000
    apply: np.log1p

  - name: households_15km
    dataframe: households
    radius: 15000
    apply: np.log1p

  - name: households_10km
    dataframe: households
    radius: 10000
    apply: np.log1p

  - name: households_5000m
    dataframe: households
    radius: 5000
    apply: np.log1p

  - name: households_3000m
    dataframe: households
    radius: 3000
    apply: np.log1p

  - name: households_1500m
    dataframe: households
    radius: 1500
    apply: np.log1p

  - name: households_800m
    dataframe: households
    radius: 800
    apply: np.log1p

  - name: households_400m
    dataframe: households
    radius: 400
    apply: np.log1p

  - name: jobs_5000m_11
    dataframe: jobs
    filters:
    - sector_id == 11
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_21
    dataframe: jobs
    filters:
    - sector_id == 21
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_22
    dataframe: jobs
    filters:
    - sector_id == 22
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_23
    dataframe: jobs
    filters:
    - sector_id == 23
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_3133
    dataframe: jobs
    filters:
    - sector_id == 3133
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_42
    dataframe: jobs
    filters:
    - sector_id == 42
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_4445
    dataframe: jobs
    filters:
    - sector_id == 4445
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_4849
    dataframe: jobs
    filters:
    - sector_id == 4849
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_51
    dataframe: jobs
    filters:
    - sector_id == 51
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_52
    dataframe: jobs
    filters:
    - sector_id == 52
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_53
    dataframe: jobs
    filters:
    - sector_id == 53
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_54
    dataframe: jobs
    filters:
    - sector_id == 54
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_55
    dataframe: jobs
    filters:
    - sector_id == 55
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_56
    dataframe: jobs
    filters:
    - sector_id == 56
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_61
    dataframe: jobs
    filters:
    - sector_id == 61
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_62
    dataframe: jobs
    filters:
    - sector_id == 62
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_71
    dataframe: jobs
    filters:
    - sector_id == 71
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_72
    dataframe: jobs
    filters:
    - sector_id == 72
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_81
    dataframe: jobs
    filters:
    - sector_id == 81
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_92
    dataframe: jobs
    filters:
    - sector_id == 92
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_agg0
    dataframe: jobs
    filters:
    - aggr_sector_id == 0
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_agg1
    dataframe: jobs
    filters:
    - aggr_sector_id == 1
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_agg2
    dataframe: jobs
    filters:
    - aggr_sector_id == 2
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_agg3
    dataframe: jobs
    filters:
    - aggr_sector_id == 3
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_agg4
    dataframe: jobs
    filters:
    - aggr_sector_id == 4
    radius: 5000
    apply: np.log1p

  - name: jobs_5000m_agg5
    dataframe: jobs
    filters:
    - aggr_sector_id == 5
    radius: 5000
    apply: np.log1p

  - name: jobs_3000m_11
    dataframe: jobs
    filters:
    - sector_id == 11
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_21
    dataframe: jobs
    filters:
    - sector_id == 21
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_22
    dataframe: jobs
    filters:
    - sector_id == 22
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_23
    dataframe: jobs
    filters:
    - sector_id == 23
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_3133
    dataframe: jobs
    filters:
    - sector_id == 3133
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_42
    dataframe: jobs
    filters:
    - sector_id == 42
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_4445
    dataframe: jobs
    filters:
    - sector_id == 4445
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_4849
    dataframe: jobs
    filters:
    - sector_id == 4849
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_51
    dataframe: jobs
    filters:
    - sector_id == 51
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_52
    dataframe: jobs
    filters:
    - sector_id == 52
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_53
    dataframe: jobs
    filters:
    - sector_id == 53
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_54
    dataframe: jobs
    filters:
    - sector_id == 54
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_55
    dataframe: jobs
    filters:
    - sector_id == 55
    radius: 3000

  - name: jobs_3000m_agg0
    dataframe: jobs
    filters:
    - aggr_sector_id == 0
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_agg1
    dataframe: jobs
    filters:
    - aggr_sector_id == 1
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_agg2
    dataframe: jobs
    filters:
    - aggr_sector_id == 2
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_agg3
    dataframe: jobs
    filters:
    - aggr_sector_id == 3
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_agg4
    dataframe: jobs
    filters:
    - aggr_sector_id == 4
    radius: 3000
    apply: np.log1p

  - name: jobs_3000m_agg5
    dataframe: jobs
    filters:
    - aggr_sector_id == 5
    radius: 3000
    apply: np.log1p

  - name: jobs_1500m_11
    dataframe: jobs
    filters:
    - sector_id == 11
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_21
    dataframe: jobs
    filters:
    - sector_id == 21
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_22
    dataframe: jobs
    filters:
    - sector_id == 22
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_23
    dataframe: jobs
    filters:
    - sector_id == 23
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_3133
    dataframe: jobs
    filters:
    - sector_id == 3133
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_42
    dataframe: jobs
    filters:
    - sector_id == 42
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_4445
    dataframe: jobs
    filters:
    - sector_id == 4445
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_4849
    dataframe: jobs
    filters:
    - sector_id == 4849
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_51
    dataframe: jobs
    filters:
    - sector_id == 51
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_52
    dataframe: jobs
    filters:
    - sector_id == 52
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_53
    dataframe: jobs
    filters:
    - sector_id == 53
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_54
    dataframe: jobs
    filters:
    - sector_id == 54
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_55
    dataframe: jobs
    filters:
    - sector_id == 55
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_56
    dataframe: jobs
    filters:
    - sector_id == 56
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_61
    dataframe: jobs
    filters:
    - sector_id == 61
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_62
    dataframe: jobs
    filters:
    - sector_id == 62
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_71
    dataframe: jobs
    filters:
    - sector_id == 71
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_72
    dataframe: jobs
    filters:
    - sector_id == 72
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_81
    dataframe: jobs
    filters:
    - sector_id == 81
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_92
    dataframe: jobs
    filters:
    - sector_id == 92
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_agg0
    dataframe: jobs
    filters:
    - aggr_sector_id == 0
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_agg1
    dataframe: jobs
    filters:
    - aggr_sector_id == 1
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_agg2
    dataframe: jobs
    filters:
    - aggr_sector_id == 2
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_agg3
    dataframe: jobs
    filters:
    - aggr_sector_id == 3
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_agg4
    dataframe: jobs
    filters:
    - aggr_sector_id == 4
    radius: 1500
    apply: np.log1p

  - name: jobs_1500m_agg5
    dataframe: jobs
    filters:
    - aggr_sector_id == 5
    radius: 1500
    apply: np.log1p

  - name: ave_income_5000m
    dataframe: households
    varname: income
    radius: 5000
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_income_3000m
    dataframe: households
    varname: income
    radius: 3000
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_income_1500m
    dataframe: households
    varname: income
    radius: 1500
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_income_800m
    dataframe: households
    varname: income
    radius: 800
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: high_income_hh_5000m
    dataframe: households
    filters:
    - income > 100000
    radius: 5000
    apply: np.log1p

  - name: high_income_hh_3000m
    dataframe: households
    filters:
    - income > 100000
    radius: 3000
    apply: np.log1p

  - name: high_income_hh_1500m
    dataframe: households
    filters:
    - income > 100000
    radius: 1500
    apply: np.log1p

  - name: low_income_hh_5000m
    dataframe: households
    filters:
    - income < 40000
    radius: 5000
    apply: np.log1p

  - name: low_income_hh_3000m
    dataframe: households
    filters:
    - income < 40000
    radius: 3000
    apply: np.log1p

  - name: low_income_hh_1500m
    dataframe: households
    filters:
    - income < 40000
    radius: 1500
    apply: np.log1p
    
  - name: ave_age_of_head_1500m
    dataframe: households
    varname: age_of_head
    radius: 1500
    aggregation: average
    decay: flat
    
  - name: ave_children_1500m
    dataframe: households
    varname: children
    radius: 1500
    aggregation: average
    decay: flat

  - name: ave_workers_1500m
    dataframe: households
    varname: workers
    radius: 1500
    aggregation: average
    decay: flat

  - name: ave_cars_1500m
    dataframe: households
    varname: cars
    radius: 1500
    aggregation: average
    decay: flat

  - name: population_1500m
    dataframe: households
    varname: persons
    radius: 1500
    aggregation: sum
    decay: flat
    apply: np.log1p

  - name: population_800m
    dataframe: households
    varname: persons
    radius: 800
    aggregation: sum
    decay: flat
    apply: np.log1p
    
  - name: population_400m
    dataframe: households
    varname: persons
    radius: 400
    aggregation: sum
    decay: flat
    apply: np.log1p

  - name: du_5000m
    dataframe: residential_units
    radius: 5000
    apply: np.log1p

  - name: du_3000m
    dataframe: residential_units
    radius: 3000
    apply: np.log1p

  - name: du_1500m
    dataframe: residential_units
    radius: 1500
    apply: np.log1p

  - name: du_800m
    dataframe: residential_units
    radius: 800
    apply: np.log1p

  - name: du_400m
    dataframe: residential_units
    radius: 400
    apply: np.log1p

  - name: ave_rent_5000m
    dataframe: residential_units
    varname: rent
    radius: 5000
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_rent_3000m
    dataframe: residential_units
    varname: rent
    radius: 3000
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_rent_1500m
    dataframe: residential_units
    varname: rent
    radius: 1500
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_rent_800m
    dataframe: residential_units
    varname: rent
    radius: 800
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_rent_400m
    dataframe: residential_units
    varname: rent
    radius: 400
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_value_5000m
    dataframe: residential_units
    varname: value
    radius: 5000
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_value_3000m
    dataframe: residential_units
    varname: value
    radius: 3000
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_value_1500m
    dataframe: residential_units
    varname: value
    radius: 1500
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_value_800m
    dataframe: residential_units
    varname: value
    radius: 800
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_value_400m
    dataframe: residential_units
    varname: value
    radius: 400
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: ave_year_built_5000m
    dataframe: residential_units
    varname: year_built
    radius: 5000
    aggregation: average
    decay: flat

  - name: ave_year_built_3000m
    dataframe: residential_units
    varname: year_built
    radius: 3000
    aggregation: average
    decay: flat

  - name: ave_year_built_1500m
    dataframe: residential_units
    varname: year_built
    radius: 1500
    aggregation: average
    decay: flat

  - name: ave_year_built_800m
    dataframe: residential_units
    varname: year_built
    radius: 800
    aggregation: average
    decay: flat

  - name: post2000_du_5000m
    dataframe: residential_units
    filters:
    - year_built > 2000
    radius: 5000
    apply: np.log1p

  - name: post2000_du_3000m
    dataframe: residential_units
    filters:
    - year_built > 2000
    radius: 3000
    apply: np.log1p

  - name: post2000_du_1500m
    dataframe: residential_units
    filters:
    - year_built > 2000
    radius: 1500
    apply: np.log1p

  - name: post2000_du_800m
    dataframe: residential_units
    filters:
    - year_built > 2000
    radius: 800
    apply: np.log1p

  - name: post2010_du_5000m
    dataframe: residential_units
    filters:
    - year_built > 2010
    radius: 5000
    apply: np.log1p

  - name: post2010_du_3000m
    dataframe: residential_units
    filters:
    - year_built > 2010
    radius: 3000
    apply: np.log1p

  - name: post2010_du_1500m
    dataframe: residential_units
    filters:
    - year_built > 2010
    radius: 1500
    apply: np.log1p

  - name: post2010_du_800m
    dataframe: residential_units
    filters:
    - year_built > 2010
    radius: 800
    apply: np.log1p

  - name: own_singlfam_du_3000m
    dataframe: residential_units
    filters:
    - building_type_id == 1
    radius: 3000
    apply: np.log1p

  - name: own_multifam_du_3000m
    dataframe: residential_units
    filters:
    - building_type_id == 2
    radius: 3000
    apply: np.log1p

  - name: rnt_singlfam_du_3000m
    dataframe: residential_units
    filters:
    - building_type_id == 3
    radius: 3000
    apply: np.log1p

  - name: rnt_multifam_du_3000m
    dataframe: residential_units
    filters:
    - building_type_id == 4
    radius: 3000
    apply: np.log1p

  - name: own_singlfam_du_1500m
    dataframe: residential_units
    filters:
    - building_type_id == 1
    radius: 1500
    apply: np.log1p

  - name: own_multifam_du_1500m
    dataframe: residential_units
    filters:
    - building_type_id == 2
    radius: 1500
    apply: np.log1p

  - name: rnt_singlfam_du_1500m
    dataframe: residential_units
    filters:
    - building_type_id == 3
    radius: 1500
    apply: np.log1p

  - name: rnt_multifam_du_1500m
    dataframe: residential_units
    filters:
    - building_type_id == 4
    radius: 1500
    apply: np.log1p

  - name: own_singlfam_du_800m
    dataframe: residential_units
    filters:
    - building_type_id == 1
    radius: 800
    apply: np.log1p

  - name: own_multifam_du_800m
    dataframe: residential_units
    filters:
    - building_type_id == 2
    radius: 800
    apply: np.log1p

  - name: rnt_singlfam_du_800m
    dataframe: residential_units
    filters:
    - building_type_id == 3
    radius: 800
    apply: np.log1p

  - name: rnt_multifam_du_800m
    dataframe: residential_units
    filters:
    - building_type_id == 4
    radius: 800
    apply: np.log1p
