name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: year_built > 2000

choosers_predict_filters: building_type_id == 1

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: block_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    block_groups_median_year_built: null
    counties_median_income: null
    density_households: null
    nodes_ave_rent_400m: null
    nodes_jobs_15km: null
    res_btype_mode1: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        block_groups_median_year_built: 0.06398717750632346
        counties_median_income: 9.803995189052718e-06
        density_households: 0.09977464318484061
        nodes_ave_rent_400m: 0.4089522093398425
        nodes_jobs_15km: 0.09346794177434799
        res_btype_mode1: 2.4957498250913486
    Std. Error:
        block_groups_median_year_built: 0.0003723606162519727
        counties_median_income: 5.0567752583198e-06
        density_households: 0.01690944816004821
        nodes_ave_rent_400m: 0.13200312810131629
        nodes_jobs_15km: 0.025578648699885152
        res_btype_mode1: 0.14026916057506206
    T-Score:
        block_groups_median_year_built: 171.84195834240424
        counties_median_income: 1.9387840448163922
        density_households: 5.90052627622569
        nodes_ave_rent_400m: 3.098049381268902
        nodes_jobs_15km: 3.6541391560988776
        res_btype_mode1: 17.79257689188067

probability_mode: single_chooser

log_likelihoods:
    convergence: -3058.286648843428
    'null': -3912.023005428176
    ratio: 0.2182339815998361
