name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: year_built > 2000

choosers_predict_filters: building_type_id == 4

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: block_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    block_groups_total_residential_units: null
    counties_median_income: null
    nodes_ave_rent_400m: null
    nodes_jobs_15km: null
    nodes_post2000_du_800m: null
    res_btype_mode4: null
    tracts_density_households: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        block_groups_total_residential_units: -0.00032632916246186686
        counties_median_income: 1.5227946763170729e-05
        nodes_ave_rent_400m: 0.23406558120944984
        nodes_jobs_15km: 0.2977890009556021
        nodes_post2000_du_800m: 1.241398842327875
        res_btype_mode4: 2.3177013306588656
        tracts_density_households: -0.5364063818951631
    Std. Error:
        block_groups_total_residential_units: 0.00011868299467636238
        counties_median_income: 7.2373900330384884e-06
        nodes_ave_rent_400m: 0.10614605833746082
        nodes_jobs_15km: 0.04744316426889529
        nodes_post2000_du_800m: 0.0450901657172533
        res_btype_mode4: 0.08255443830266934
        tracts_density_households: 0.08884158338452176
    T-Score:
        block_groups_total_residential_units: -2.7495865212344572
        counties_median_income: 2.104066064376186
        nodes_ave_rent_400m: 2.2051273959255813
        nodes_jobs_15km: 6.276752521560597
        nodes_post2000_du_800m: 27.53147659984905
        res_btype_mode4: 28.074824059264714
        tracts_density_households: -6.03778502656243

probability_mode: single_chooser

log_likelihoods:
    convergence: -1931.4948135233494
    'null': -3912.023005428176
    ratio: 0.5062670104845294
