{alts_fit_filters: null, alts_predict_filters: null, choice_column: block_id, choice_mode: aggregate,
  choosers_fit_filters: year_built > 2000, choosers_predict_filters: building_type_id
    == 3, estimation_sample_size: 1000, fit_parameters: {Coefficient: {county_id_is_27009: -0.06,
      county_id_is_27141: -0.06, county_id_is_27145: 0.06, density_residential_units: 0.07089231757026535,
      median_year_built: 0.05915219169907564, nodes_ave_rent_400m: 2.092913540004155,
      nodes_high_income_hh_1500m: 0.14898413106829173, nodes_jobs_10km: 0.04837068396187433,
      res_btype_mode4: 0.7300642273608986, total_residential_units: 0.010040768539143945,
      tracts_ratio_households_to_residential_units: 3.0}, Std. Error: {density_residential_units: 0.00832439834625041,
      median_year_built: 0.0004906704248671312, nodes_ave_rent_400m: 0.12820221218439248,
      nodes_high_income_hh_1500m: 0.04049311071851773, nodes_jobs_10km: 0.027727665674322905,
      res_btype_mode4: 0.10472007808889601, total_residential_units: 0.0005354852135633373,
      tracts_ratio_households_to_residential_units: 0.9563937865174345}, T-Score: {
      density_residential_units: 8.51620917470842, median_year_built: 120.55381515014581,
      nodes_ave_rent_400m: 16.325096925737363, nodes_high_income_hh_1500m: 3.6792463810432925,
      nodes_jobs_10km: 1.7444917480618576, res_btype_mode4: 6.971578332296058, total_residential_units: 18.750785801028137,
      tracts_ratio_households_to_residential_units: 3.1367832395942816}}, fitted: true,
  interaction_predict_filters: null, log_likelihoods: {convergence: -2659.0111007597197,
    'null': -3912.023005428176, ratio: 0.3202976830478308}, model_expression: !!set {
    county_id_is_27009: null, county_id_is_27141: null, county_id_is_27145: null,
    density_residential_units: null, median_year_built: null, nodes_ave_rent_400m: null,
    nodes_high_income_hh_1500m: null, nodes_jobs_10km: null, res_btype_mode4: null,
    total_residential_units: null, tracts_ratio_households_to_residential_units: null},
  model_type: discretechoice, name: MNLDiscreteChoiceModel, prediction_sample_size: null,
  probability_mode: single_chooser, sample_size: 50}
