name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: year_built > 2000

choosers_predict_filters: building_type_id == 4

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 50

estimation_sample_size: 1000

prediction_sample_size: null

model_expression: !!set
    median_year_built: null
    nodes_jobs_10km: null
    res_btype_mode4: null
    res_rent: null
    total_households: null

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        median_year_built: 0.029156683785401427
        nodes_jobs_10km: 0.2090669037861001
        res_btype_mode4: 1.2580590340554256
        res_rent: 0.00013580725570800658
        total_households: 0.0011075562438943724
    Std. Error:
        median_year_built: 0.00015154260836938913
        nodes_jobs_10km: 0.02642133530063322
        res_btype_mode4: 0.07608457932722684
        res_rent: 0.00011502547833803759
        total_households: 7.231420781892641e-05
    T-Score:
        median_year_built: 192.39924730826354
        nodes_jobs_10km: 7.912806124567426
        res_btype_mode4: 16.535006767202162
        res_rent: 1.1806710797489177
        total_households: 15.315887116784504

probability_mode: single_chooser

log_likelihoods:
    convergence: -3389.1925226370804
    'null': -3912.023005428176
    ratio: 0.13364708798124036
