name: RegressionModel

model_type: regression

fit_filters:
- res_values > 0
- value_impute==0

predict_filters: all_zones == 1

model_expression:
    left_side: res_values
    right_side: !!set
        block_groups_mean_income: null
        block_groups_mean_year_built: null
        density_households: null
        res_btype_mode1: null

ytransform: null

fitted: true

fit_parameters:
    Coefficient:
        Intercept: -657767.6683290352
        block_groups_mean_income: 1.5325288336191631
        block_groups_mean_year_built: 370.4448090061999
        density_households: -3512.753267414993
        res_btype_mode1: -65.9088203105648
    Std. Error:
        Intercept: 74937.263649951
        block_groups_mean_income: 0.028328954181375328
        block_groups_mean_year_built: 38.35567833275323
        density_households: 228.82300409240258
        res_btype_mode1: 1066.812704623822
    T-Score:
        Intercept: -8.777577887039184
        block_groups_mean_income: 54.097614186785385
        block_groups_mean_year_built: 9.65814776608616
        density_households: -15.35139913641062
        res_btype_mode1: -0.061781060560021625

fit_rsquared_adj: 0.48431650677402693

fit_rsquared: 0.48460106105363854
