name: RegressionModel

model_type: regression

fit_filters:
- res_rents > 0
- rent_impute==0

predict_filters: all_zones == 1

model_expression:
    left_side: res_rents
    right_side: !!set
        block_groups_density_jobs: null
        counties_median_income: null
        nodes_ave_year_built_5000m: null
        nodes_jobs_35km: null
        pumas_ratio_households_to_residential_units: null
        res_btype_mode4: null

ytransform: null

fitted: true

fit_parameters:
    Coefficient:
        Intercept: -15655.660291199516
        block_groups_density_jobs: -5.637623291191394
        counties_median_income: 0.009389397375496478
        nodes_ave_year_built_5000m: 6.2502475568711
        nodes_jobs_35km: 57.03337925292596
        pumas_ratio_households_to_residential_units: 3165.351972552039
        res_btype_mode4: -37.5013713476005
    Std. Error:
        Intercept: 607.2355734244205
        block_groups_density_jobs: 0.8425621645589915
        counties_median_income: 0.00038743065818440804
        nodes_ave_year_built_5000m: 0.3154020073904735
        nodes_jobs_35km: 2.1698987469294027
        pumas_ratio_households_to_residential_units: 194.4057789505533
        res_btype_mode4: 7.023399411461744
    T-Score:
        Intercept: -25.781856294932787
        block_groups_density_jobs: -6.691047293990708
        counties_median_income: 24.23503968296526
        nodes_ave_year_built_5000m: 19.816765304011454
        nodes_jobs_35km: 26.283889667033176
        pumas_ratio_households_to_residential_units: 16.282190733420222
        res_btype_mode4: -5.3394900603831

fit_rsquared_adj: 0.41261756968553986

fit_rsquared: 0.4131037463418906
